version: '3.9'

services:

  mysql_db:
    container_name: mysql_container
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: erick123
      MYSQL_DATABASE: school_db
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: erick123
    depends_on:
      - mysql_db

  django:
    container_name: django_container
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql_db

networks:
  default:
    driver: bridge

volumes:
  db_data:
