# Generated by Django 5.0.7 on 2024-07-26 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_school_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_school', to=settings.AUTH_USER_MODEL),
        ),
    ]
